"""initial schema

Revision ID: 75cdab8db7a4
Revises: 
Create Date: 2026-09-01 11:03:13.628105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75cdab8db7a4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_index',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('index_value', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('districts',
    sa.Column('district_id', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('terrain_category', sa.Enum('PLAIN', 'HILLY', 'REMOTE', 'COASTAL', 'URBAN', name='terrain', native_enum=False, length=32), nullable=False),
    sa.Column('centroid_lat', sa.Float(), nullable=False),
    sa.Column('centroid_lon', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('district_id')
    )
    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_districts_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_districts_terrain_category'), ['terrain_category'], unique=False)

    op.create_table('engine_config',
    sa.Column('config_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=48), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('config_id'),
    sa.UniqueConstraint('scope', 'key', name='uq_engine_config_scope_key')
    )
    with op.batch_alter_table('engine_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engine_config_scope'), ['scope'], unique=False)

    op.create_table('mps',
    sa.Column('mp_id', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('house', sa.Enum('LOK_SABHA', 'RAJYA_SABHA', 'NOMINATED', name='house', native_enum=False, length=32), nullable=False),
    sa.Column('constituency', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('tenure_start', sa.Date(), nullable=False),
    sa.Column('tenure_end', sa.Date(), nullable=False),
    sa.Column('annual_entitlement', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('mp_id')
    )
    with op.batch_alter_table('mps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mps_state'), ['state'], unique=False)

    op.create_table('sor_benchmarks',
    sa.Column('sor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('work_type', sa.String(length=48), nullable=False),
    sa.Column('unit', sa.String(length=24), nullable=False),
    sa.Column('unit_rate', sa.Float(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('terrain_category', sa.Enum('PLAIN', 'HILLY', 'REMOTE', 'COASTAL', 'URBAN', name='terrain', native_enum=False, length=32), nullable=False),
    sa.Column('terrain_multiplier', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('sor_id'),
    sa.UniqueConstraint('state', 'work_type', 'year', 'terrain_category', name='uq_sor_state_type_year_terrain')
    )
    with op.batch_alter_table('sor_benchmarks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sor_benchmarks_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_sor_benchmarks_terrain_category'), ['terrain_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_sor_benchmarks_work_type'), ['work_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sor_benchmarks_year'), ['year'], unique=False)

    op.create_table('agencies',
    sa.Column('agency_id', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('agency_type', sa.Enum('PWD', 'PRI', 'MUNICIPAL', 'LINE_DEPARTMENT', 'OTHER', name='agencytype', native_enum=False, length=32), nullable=False),
    sa.Column('district_id', sa.String(length=24), nullable=False),
    sa.Column('registered_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.district_id'], ),
    sa.PrimaryKeyConstraint('agency_id')
    )
    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agencies_district_id'), ['district_id'], unique=False)

    op.create_table('user_agencies',
    sa.Column('user_agency_id', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('user_agency_type', sa.Enum('SCHOOL', 'PANCHAYAT', 'HEALTH_CENTRE', 'MUNICIPAL_BODY', 'LINE_DEPARTMENT', 'OTHER', name='useragencytype', native_enum=False, length=32), nullable=False),
    sa.Column('district_id', sa.String(length=24), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.district_id'], ),
    sa.PrimaryKeyConstraint('user_agency_id')
    )
    with op.batch_alter_table('user_agencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_agencies_district_id'), ['district_id'], unique=False)

    op.create_table('users',
    sa.Column('user_id', sa.String(length=48), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('DISTRICT_AUTHORITY', 'MP', 'MINISTRY', 'STATE_NODAL', 'IMPLEMENTING_AGENCY', 'USER_AGENCY', 'PUBLIC', name='role', native_enum=False, length=32), nullable=False),
    sa.Column('scope_state', sa.String(length=80), nullable=True),
    sa.Column('scope_district_id', sa.String(length=24), nullable=True),
    sa.Column('scope_mp_id', sa.String(length=24), nullable=True),
    sa.Column('scope_agency_id', sa.String(length=24), nullable=True),
    sa.Column('scope_user_agency_id', sa.String(length=24), nullable=True),
    sa.ForeignKeyConstraint(['scope_agency_id'], ['agencies.agency_id'], ),
    sa.ForeignKeyConstraint(['scope_district_id'], ['districts.district_id'], ),
    sa.ForeignKeyConstraint(['scope_mp_id'], ['mps.mp_id'], ),
    sa.ForeignKeyConstraint(['scope_user_agency_id'], ['user_agencies.user_agency_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('firebase_uid')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('works',
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('mp_id', sa.String(length=24), nullable=True),
    sa.Column('district_id', sa.String(length=24), nullable=False),
    sa.Column('block', sa.String(length=80), nullable=False),
    sa.Column('panchayat', sa.String(length=80), nullable=True),
    sa.Column('work_type', sa.String(length=48), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('final_cost', sa.Float(), nullable=True),
    sa.Column('recommended_date', sa.Date(), nullable=True),
    sa.Column('sanctioned_date', sa.Date(), nullable=True),
    sa.Column('expected_completion_date', sa.Date(), nullable=True),
    sa.Column('actual_completion_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('RECOMMENDED', 'SANCTIONED', 'IN_PROGRESS', 'COMPLETED', 'REJECTED', name='workstatus', native_enum=False, length=32), nullable=False),
    sa.Column('agency_id', sa.String(length=24), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('is_sc_st_area', sa.Boolean(), nullable=False),
    sa.Column('planted_anomaly', sa.Enum('COST_INFLATION', 'DUPLICATE_WORK', 'SALAMI_SLICING', 'PAYMENT_AHEAD', 'GEOTAG_MISMATCH', 'PHOTO_REUSE', 'TIMELINE_BREACH', 'COST_OVERRUN', 'GHOST_WORK', 'ENTITLEMENT_BREACH', 'QUOTA_SHORTFALL', 'HANDOVER_GAP', name='plantedanomaly', native_enum=False, length=32), nullable=True),
    sa.Column('description_embedding', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.agency_id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.district_id'], ),
    sa.ForeignKeyConstraint(['mp_id'], ['mps.mp_id'], ),
    sa.PrimaryKeyConstraint('work_id')
    )
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_works_agency_id'), ['agency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_works_block'), ['block'], unique=False)
        batch_op.create_index(batch_op.f('ix_works_district_id'), ['district_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_works_mp_id'), ['mp_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_works_planted_anomaly'), ['planted_anomaly'], unique=False)
        batch_op.create_index(batch_op.f('ix_works_recommended_date'), ['recommended_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_works_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_works_work_type'), ['work_type'], unique=False)

    op.create_table('asset_handovers',
    sa.Column('handover_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('user_agency_id', sa.String(length=24), nullable=False),
    sa.Column('handover_initiated_date', sa.Date(), nullable=False),
    sa.Column('handover_acknowledged_date', sa.Date(), nullable=True),
    sa.Column('uc_submitted_date', sa.Date(), nullable=True),
    sa.Column('register_entry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['user_agency_id'], ['user_agencies.user_agency_id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.work_id'], ),
    sa.PrimaryKeyConstraint('handover_id')
    )
    with op.batch_alter_table('asset_handovers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_handovers_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_handovers_user_agency_id'), ['user_agency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_handovers_work_id'), ['work_id'], unique=True)

    op.create_table('completion_photos',
    sa.Column('photo_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('upload_date', sa.Date(), nullable=False),
    sa.Column('capture_timestamp', sa.DateTime(), nullable=True),
    sa.Column('photo_lat', sa.Float(), nullable=True),
    sa.Column('photo_lon', sa.Float(), nullable=True),
    sa.Column('stage', sa.Enum('START', 'MID', 'COMPLETE', name='photostage', native_enum=False, length=32), nullable=False),
    sa.Column('image_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['work_id'], ['works.work_id'], ),
    sa.PrimaryKeyConstraint('photo_id')
    )
    with op.batch_alter_table('completion_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_completion_photos_image_hash'), ['image_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_completion_photos_work_id'), ['work_id'], unique=False)

    op.create_table('lifecycle_checkins',
    sa.Column('checkin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('checkin_date', sa.Date(), nullable=False),
    sa.Column('photo_reference', sa.String(length=512), nullable=True),
    sa.Column('still_in_use', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['work_id'], ['works.work_id'], ),
    sa.PrimaryKeyConstraint('checkin_id')
    )
    with op.batch_alter_table('lifecycle_checkins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lifecycle_checkins_work_id'), ['work_id'], unique=False)

    op.create_table('maintenance_recommendations',
    sa.Column('recommendation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('user_agency_id', sa.String(length=24), nullable=False),
    sa.Column('raised_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('photo_reference', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('da_response', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_agency_id'], ['user_agencies.user_agency_id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.work_id'], ),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    with op.batch_alter_table('maintenance_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_recommendations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_recommendations_user_agency_id'), ['user_agency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_recommendations_work_id'), ['work_id'], unique=False)

    op.create_table('payments',
    sa.Column('payment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('installment_no', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('reported_physical_progress_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['works.work_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_work_id'), ['work_id'], unique=False)

    op.create_table('progress_reports',
    sa.Column('report_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('physical_progress_pct', sa.Float(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['work_id'], ['works.work_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    with op.batch_alter_table('progress_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_progress_reports_report_date'), ['report_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_reports_work_id'), ['work_id'], unique=False)

    op.create_table('risk_assessments',
    sa.Column('assessment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.Enum('STAGE_1', 'STAGE_2', 'STAGE_3', name='stage', native_enum=False, length=32), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('severity_tier', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severitytier', native_enum=False, length=32), nullable=False),
    sa.Column('engine_version', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['works.work_id'], ),
    sa.PrimaryKeyConstraint('assessment_id')
    )
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_assessments_severity_tier'), ['severity_tier'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_assessments_stage'), ['stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_assessments_work_id'), ['work_id'], unique=False)

    op.create_table('module_contributions',
    sa.Column('contribution_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('module', sa.Enum('COST', 'DUPLICATE', 'AGENCY', 'COMPLIANCE', 'STATISTICAL', 'DISBURSEMENT', 'GEOTAG', 'VARIANCE', 'TIMELINE', 'HANDOVER', name='modulecode', native_enum=False, length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['risk_assessments.assessment_id'], ),
    sa.PrimaryKeyConstraint('contribution_id'),
    sa.UniqueConstraint('assessment_id', 'module', name='uq_contribution_assessment_module')
    )
    with op.batch_alter_table('module_contributions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_module_contributions_assessment_id'), ['assessment_id'], unique=False)

    op.create_table('risk_flags',
    sa.Column('flag_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('module', sa.Enum('COST', 'DUPLICATE', 'AGENCY', 'COMPLIANCE', 'STATISTICAL', 'DISBURSEMENT', 'GEOTAG', 'VARIANCE', 'TIMELINE', 'HANDOVER', name='modulecode', native_enum=False, length=32), nullable=False),
    sa.Column('flag_code', sa.String(length=48), nullable=False),
    sa.Column('signal_value', sa.Float(), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('severity_tier', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severitytier', native_enum=False, length=32), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_INVESTIGATION', 'OVERRIDDEN', 'CLEARED', name='flagstatus', native_enum=False, length=32), nullable=False),
    sa.Column('assigned_to_user_id', sa.String(length=48), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['risk_assessments.assessment_id'], ),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.work_id'], ),
    sa.PrimaryKeyConstraint('flag_id')
    )
    with op.batch_alter_table('risk_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_flags_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_flags_assigned_to_user_id'), ['assigned_to_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_flags_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_flags_flag_code'), ['flag_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_flags_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_flags_severity_tier'), ['severity_tier'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_flags_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_flags_work_id'), ['work_id'], unique=False)

    op.create_table('agency_responses',
    sa.Column('response_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flag_id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.String(length=24), nullable=False),
    sa.Column('submitted_date', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('evidence_reference', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.agency_id'], ),
    sa.ForeignKeyConstraint(['flag_id'], ['risk_flags.flag_id'], ),
    sa.PrimaryKeyConstraint('response_id')
    )
    with op.batch_alter_table('agency_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agency_responses_agency_id'), ['agency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agency_responses_flag_id'), ['flag_id'], unique=False)

    op.create_table('flag_reviews',
    sa.Column('review_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flag_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_role', sa.Enum('DISTRICT_AUTHORITY', 'MP', 'MINISTRY', 'STATE_NODAL', 'IMPLEMENTING_AGENCY', 'USER_AGENCY', 'PUBLIC', name='role', native_enum=False, length=32), nullable=False),
    sa.Column('reviewer_name', sa.String(length=120), nullable=False),
    sa.Column('action', sa.Enum('INVESTIGATE', 'OVERRIDE', 'CLEAR', name='reviewaction', native_enum=False, length=32), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['flag_id'], ['risk_flags.flag_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    with op.batch_alter_table('flag_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flag_reviews_decided_at'), ['decided_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_flag_reviews_flag_id'), ['flag_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flag_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flag_reviews_flag_id'))
        batch_op.drop_index(batch_op.f('ix_flag_reviews_decided_at'))

    op.drop_table('flag_reviews')
    with op.batch_alter_table('agency_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agency_responses_flag_id'))
        batch_op.drop_index(batch_op.f('ix_agency_responses_agency_id'))

    op.drop_table('agency_responses')
    with op.batch_alter_table('risk_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_flags_work_id'))
        batch_op.drop_index(batch_op.f('ix_risk_flags_status'))
        batch_op.drop_index(batch_op.f('ix_risk_flags_severity_tier'))
        batch_op.drop_index(batch_op.f('ix_risk_flags_module'))
        batch_op.drop_index(batch_op.f('ix_risk_flags_flag_code'))
        batch_op.drop_index(batch_op.f('ix_risk_flags_created_at'))
        batch_op.drop_index(batch_op.f('ix_risk_flags_assigned_to_user_id'))
        batch_op.drop_index(batch_op.f('ix_risk_flags_assessment_id'))

    op.drop_table('risk_flags')
    with op.batch_alter_table('module_contributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_module_contributions_assessment_id'))

    op.drop_table('module_contributions')
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_assessments_work_id'))
        batch_op.drop_index(batch_op.f('ix_risk_assessments_stage'))
        batch_op.drop_index(batch_op.f('ix_risk_assessments_severity_tier'))

    op.drop_table('risk_assessments')
    with op.batch_alter_table('progress_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_progress_reports_work_id'))
        batch_op.drop_index(batch_op.f('ix_progress_reports_report_date'))

    op.drop_table('progress_reports')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_work_id'))

    op.drop_table('payments')
    with op.batch_alter_table('maintenance_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_recommendations_work_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_recommendations_user_agency_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_recommendations_status'))

    op.drop_table('maintenance_recommendations')
    with op.batch_alter_table('lifecycle_checkins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lifecycle_checkins_work_id'))

    op.drop_table('lifecycle_checkins')
    with op.batch_alter_table('completion_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_completion_photos_work_id'))
        batch_op.drop_index(batch_op.f('ix_completion_photos_image_hash'))

    op.drop_table('completion_photos')
    with op.batch_alter_table('asset_handovers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_handovers_work_id'))
        batch_op.drop_index(batch_op.f('ix_asset_handovers_user_agency_id'))
        batch_op.drop_index(batch_op.f('ix_asset_handovers_status'))

    op.drop_table('asset_handovers')
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_works_work_type'))
        batch_op.drop_index(batch_op.f('ix_works_status'))
        batch_op.drop_index(batch_op.f('ix_works_recommended_date'))
        batch_op.drop_index(batch_op.f('ix_works_planted_anomaly'))
        batch_op.drop_index(batch_op.f('ix_works_mp_id'))
        batch_op.drop_index(batch_op.f('ix_works_district_id'))
        batch_op.drop_index(batch_op.f('ix_works_block'))
        batch_op.drop_index(batch_op.f('ix_works_agency_id'))

    op.drop_table('works')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))

    op.drop_table('users')
    with op.batch_alter_table('user_agencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_agencies_district_id'))

    op.drop_table('user_agencies')
    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agencies_district_id'))

    op.drop_table('agencies')
    with op.batch_alter_table('sor_benchmarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sor_benchmarks_year'))
        batch_op.drop_index(batch_op.f('ix_sor_benchmarks_work_type'))
        batch_op.drop_index(batch_op.f('ix_sor_benchmarks_terrain_category'))
        batch_op.drop_index(batch_op.f('ix_sor_benchmarks_state'))

    op.drop_table('sor_benchmarks')
    with op.batch_alter_table('mps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mps_state'))

    op.drop_table('mps')
    with op.batch_alter_table('engine_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engine_config_scope'))

    op.drop_table('engine_config')
    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_districts_terrain_category'))
        batch_op.drop_index(batch_op.f('ix_districts_state'))

    op.drop_table('districts')
    op.drop_table('cost_index')
    # ### end Alembic commands ###
