"""citizen submissions

Revision ID: aa63931f04d5
Revises: 75cdab8db7a4
Create Date: 2026-09-01 15:33:22.032543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa63931f04d5'
down_revision: Union[str, None] = '75cdab8db7a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citizen_submissions',
    sa.Column('submission_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_type', sa.String(length=24), nullable=False),
    sa.Column('district_id', sa.String(length=24), nullable=False),
    sa.Column('block', sa.String(length=80), nullable=True),
    sa.Column('related_work_id', sa.String(length=32), nullable=True),
    sa.Column('suggested_work_type', sa.String(length=48), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('submitter_name', sa.String(length=120), nullable=False),
    sa.Column('submitter_contact', sa.String(length=160), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('official_response', sa.Text(), nullable=True),
    sa.Column('responded_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.district_id'], ),
    sa.ForeignKeyConstraint(['related_work_id'], ['works.work_id'], ),
    sa.PrimaryKeyConstraint('submission_id')
    )
    with op.batch_alter_table('citizen_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_citizen_submissions_district_id'), ['district_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_citizen_submissions_related_work_id'), ['related_work_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_citizen_submissions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_citizen_submissions_submission_type'), ['submission_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_citizen_submissions_submitted_at'), ['submitted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citizen_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_citizen_submissions_submitted_at'))
        batch_op.drop_index(batch_op.f('ix_citizen_submissions_submission_type'))
        batch_op.drop_index(batch_op.f('ix_citizen_submissions_status'))
        batch_op.drop_index(batch_op.f('ix_citizen_submissions_related_work_id'))
        batch_op.drop_index(batch_op.f('ix_citizen_submissions_district_id'))

    op.drop_table('citizen_submissions')
    # ### end Alembic commands ###
